[package]
name = "iceoryx2-bb-linux"
description = "iceoryx2: [internal] high level safe abstractions for low level unsafe linux constructs"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
# Use https://crates.io/crates/libc for the platform abstraction. This simplifies
# cross-compilation since bindgen is not required anymore. Unfortunately, the libc crate
# does not offer all the functionality iceoryx2 requires on all of the supported
# platforms. Therefore, only a subset of the supported platforms will work with this
# feature flag.
libc_platform = ["iceoryx2-bb-posix/libc_platform", "iceoryx2-pal-posix/libc_platform", "iceoryx2-pal-os-api/libc_platform"]

[dependencies]
iceoryx2-log = { workspace = true }
iceoryx2-bb-concurrency = { workspace = true }
iceoryx2-bb-container = { workspace = true }
iceoryx2-bb-posix = { workspace = true }
iceoryx2-bb-system-types = { workspace = true }
iceoryx2-pal-os-api = { workspace = true }
iceoryx2-pal-posix = { workspace = true }

[dev-dependencies]
iceoryx2-bb-loggers = { workspace = true }
iceoryx2-bb-testing = { workspace = true }
iceoryx2-pal-testing = { workspace = true }
