[package]
name = "iceoryx2-tunnel"
description = "iceoryx2: the generic tunnel implementation"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]
name = "iceoryx2_tunnel"
path = "src/lib.rs"

[dependencies]
iceoryx2 = { workspace = true }
iceoryx2-bb-container = { workspace = true }
iceoryx2-bb-concurrency = { workspace = true }
iceoryx2-log = { workspace = true }
iceoryx2-tunnel-backend = { workspace = true }
iceoryx2-services-discovery = { workspace = true }

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
generic-tests = { workspace = true }
iceoryx2-bb-posix = { workspace = true }
