[package]
name = "iceoryx2-bb-elementary-tests-nostd"
description = "iceoryx2: [internal] nostd deployment of iceoryx2-bb-elementary tests"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
# Default to noop to support std workspace builds
default = ["std"]

std = [
  "iceoryx2-bb-testing-nostd-macros/std",
  "iceoryx2-bb-testing-nostd/std"
]

[dependencies]
iceoryx2-bb-elementary-traits = { workspace = true }
iceoryx2-bb-elementary-tests-common = { workspace = true }
iceoryx2-bb-loggers = { workspace = true }
iceoryx2-bb-memory = { workspace = true }
iceoryx2-bb-testing-nostd-macros = { workspace = true }
iceoryx2-bb-testing-nostd = { workspace = true }
