[package]
name = "iceoryx2-tunnel-zenoh"
description = "iceoryx2: zenoh backend for the tunnel"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]
name = "iceoryx2_tunnel_zenoh"
path = "src/lib.rs"

[dependencies]
iceoryx2 = { workspace = true }
iceoryx2-tunnel-backend = { workspace = true }
iceoryx2-log = { workspace = true }
iceoryx2-bb-concurrency = { workspace = true }

serde_json = { workspace = true }
zenoh = { workspace = true }

[dev-dependencies]
iceoryx2-bb-posix = { workspace = true }
iceoryx2-bb-testing = { workspace = true }
iceoryx2-tunnel-conformance-tests = { workspace = true }
