[package]
name = "iceoryx2-services-discovery"
description = "iceoryx2: discovery services"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
readme = "../README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]
name = "iceoryx2_services_discovery"
path = "src/lib.rs"

[dependencies]
iceoryx2 = { workspace = true }
iceoryx2-bb-elementary = { workspace = true }
iceoryx2-bb-elementary-traits = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
iceoryx2-pal-testing = { workspace = true }
iceoryx2-bb-posix = { workspace = true }
generic-tests = { workspace = true }
