[package]
name = "iceoryx2-bb-loggers"
description = "iceoryx2: [internal] swappable logger implementations"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[features]
default = []

# Use the std module
std = [
  "iceoryx2-bb-print/std",
  "iceoryx2-pal-concurrency-sync/std"
]
# Use POSIX APIs
posix = [
  "iceoryx2-bb-print/posix",
  "iceoryx2-pal-posix"
]

# Enables logging to buffer
buffer = []
# Enables logging to console
console = []
# Enables logging to file
file = []
# Enables https://crates.io/crates/log as default logger
log = ["dep:log"]
# Enables https://crates.io/crates/tracing as default logger
tracing = ["dep:tracing"]

[dependencies]
iceoryx2-log-types = { workspace = true }
iceoryx2-bb-print = { workspace = true }
iceoryx2-pal-posix = { workspace = true, optional = true }
iceoryx2-pal-concurrency-sync = { workspace = true }

log = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
