[workspace]
resolver = "2"
members = [
    "publish-subscribe/",
    "event/"
]

[workspace.package]
edition = "2021"
version = "0.8.999"
license = "MIT OR Apache-2.0"
rust-version = "1.83"

[workspace.dependencies]
posix-nostd-common = { path = "_common/" }
posix-nostd-publish-subscribe = { path = "publish-subscribe/" }
posix-nostd-event = { path = "event/" }

iceoryx2 = { path = "../../../../iceoryx2/", default-features = false }
iceoryx2-bb-loggers = { path = "../../../../iceoryx2-bb/loggers", default-features = false, features = ["posix", "console"]}
iceoryx2-bb-elementary-traits = { path = "../../../../iceoryx2-bb/elementary-traits" }
iceoryx2-bb-memory = { path = "../../../../iceoryx2-bb/memory" }
iceoryx2-bb-posix = { path = "../../../../iceoryx2-bb/posix" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
