[package]
name = "iceoryx2-bb-elementary"
description = "iceoryx2: [internal] elementary constructs that have (almost) no dependencies at all"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[features]
default = ["std"]

std = [
  "iceoryx2-bb-concurrency/std",
]

[dependencies]
iceoryx2-bb-concurrency = { workspace = true }
iceoryx2-bb-elementary-traits = { workspace = true }

[dev-dependencies]
iceoryx2-bb-elementary-tests-common = { workspace = true }
iceoryx2-bb-loggers = { workspace = true }
iceoryx2-bb-testing = { workspace = true }
iceoryx2-bb-testing-nostd-macros = { workspace = true }
iceoryx2-bb-testing-nostd = { workspace = true }

generic-tests = { workspace = true }
