[package]
name = "iceoryx2-bb-elementary"
description = "Iceoryx2: [internal] elementary constructs that have no dependencies at all"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dev-dependencies]
iceoryx2-bb-container = { workspace = true }
iceoryx2-bb-memory = { workspace = true }
iceoryx2-bb-lock-free = { workspace = true }
iceoryx2-bb-testing = { workspace = true }

generic-tests = { workspace = true }
pin-init = { workspace = true }

