[package]
name = "iceoryx2-pal-configuration"
description = "iceoryx2: [internal] platform specific settings"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
# Uses a custom configuration file for the iceoryx2 platform abstraction layer
# The location of the config can be set via environment variable
# `IOX2_CUSTOM_PAL_CONFIG_PATH`.
custom_pal_config = []

[build-dependencies]
