[package]
name = "iceoryx2-bb-container"
description = "iceoryx2: IPC shared memory compatible containers"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iceoryx2-bb-derive-macros = { workspace = true }
iceoryx2-bb-elementary = { workspace = true }
iceoryx2-bb-elementary-traits = { workspace = true }
iceoryx2-bb-log = { workspace = true }
iceoryx2-pal-concurrency-sync = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
generic-tests = { workspace = true }
iceoryx2-bb-testing = { workspace = true }
iceoryx2-pal-testing = { workspace = true }
serde_test = { workspace = true }
