[package]
name = "iceoryx2-pal-posix"
description = "iceoryx2: [internal] A posix layer that ensures uniform posix behavior on all platforms according to https://posix.opengroup.org"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[build-dependencies]
cc = { workspace = true }
bindgen = { workspace = true }

[features]
acl = []

[dependencies]
iceoryx2-pal-concurrency-sync = { workspace = true }
lazy_static = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true }
