[package]
name = "iceoryx2-bb-system-types"
description = "Iceoryx2: [internal] strong types that represents low level constructs like file, path, ip address, etc..."
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
iceoryx2-bb-container = { workspace = true }
iceoryx2-bb-log = { workspace = true }
iceoryx2-pal-configuration = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
