[global]
root-path-unix = '/tmp/iceoryx2/'
root-path-windows = 'c:\Temp\iceoryx2\'
prefix = 'iox2_'

[global.node]
directory = 'nodes'
monitor-suffix = '.node_monitor'
static-config-suffix = '.details'
service-tag-suffix = '.service_tag'
cleanup-dead-nodes-on-creation = true
cleanup-dead-nodes-on-destruction = true

[global.service]
directory = 'services'
data-segment-suffix = '.data'
static-config-storage-suffix = '.service'
dynamic-config-storage-suffix = '.dynamic'
event-connection-suffix = '.event'
connection-suffix = '.connection'
creation-timeout.secs = 0
creation-timeout.nanos = 500000000

[defaults.request-response]
client-expired-connection-buffer = 128
client-unable-to-deliver-strategy = 'Block'     # or 'DiscardSample'
enable-fire-and-forget-requests = true
enable-safe-overflow-for-requests = true
enable-safe-overflow-for-responses = true
max-active-requests-per-client = 4
max-response-buffer-size = 2
max-servers = 2
max-clients = 8
max-nodes = 20
max-borrowed-responses-per-pending-response = 2
max-loaned-requests = 2
server-expired-connection-buffer = 128
server-max-loaned-responses-per-request = 2
server-unable-to-deliver-strategy = 'Block'     # or 'DiscardSample'

[defaults.publish-subscribe]
max-subscribers = 8
max-publishers = 2
max-nodes = 20
publisher-history-size = 0
subscriber-max-buffer-size = 2
subscriber-max-borrowed-samples = 2
publisher-max-loaned-samples = 2
enable-safe-overflow = true
unable-to-deliver-strategy = 'Block'       # or 'DiscardSample'
subscriber-expired-connection-buffer = 128

[defaults.event]
max-listeners = 16
max-notifiers = 16
max-nodes = 36
event-id-max-value = 4294967295
# deadline.secs                               = 1 # uncomment to enable deadline
# deadline.nanos                              = 0 # uncomment to enable deadline
# notifier-created-event                      = 1 # uncomment to enable setting
# notifier-dropped-event                      = 2 # uncomment to enable setting
# notifier-dead-event                         = 3 # uncomment to enable setting
