[package]
name = "example"
description = "Iceoryx2 examples"
rust-version = { workspace = true }
version = { workspace = true }
repository = { workspace = true }
edition = { workspace = true }

[dependencies]
iceoryx2 = { workspace = true }

[lib]
name = "transmission_data"
path = "src/transmission_data.rs"

[[example]]
name = "discovery"
path = "examples/discovery/discovery.rs"

[[example]]
name = "event_listener"
path = "examples/event/listener.rs"

[[example]]
name = "event_notifier"
path = "examples/event/notifier.rs"

[[example]]
name = "publish_subscribe_publisher"
path = "examples/publish_subscribe/publisher.rs"

[[example]]
name = "publish_subscribe_subscriber"
path = "examples/publish_subscribe/subscriber.rs"
