[package]
name = "bare-metal-nostd-common"
description = "common components for nostd examples that run on bare metal"
version = "0.1.0"
edition = "2021"

[features]
default = []
semihosting = []

[dependencies]
iceoryx2-bb-memory = { workspace = true }
iceoryx2-bb-concurrency = { workspace = true }
