[package]
name = "iceoryx2-bb-lock-free"
description = "iceoryx2: [internal] lock-free containers and constructs"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
iceoryx2-bb-log = { workspace = true }
iceoryx2-bb-elementary = { workspace = true }
iceoryx2-bb-elementary-traits = { workspace = true }
iceoryx2-pal-concurrency-sync = { workspace = true }

[dev-dependencies]
iceoryx2-bb-posix = { workspace = true }
iceoryx2-bb-testing = { workspace = true }
iceoryx2-pal-testing = { workspace = true }
generic-tests = { workspace = true }
