[package]
name = "iceoryx2-loggers"
description = "iceoryx2: swappable logger implementations"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[features]
default = []

std_buffer = ["std", "buffer"]
std_file = ["std", "file"]
std_console = ["std", "console"]
std_log = ["std", "log"]
std_tracing = ["std", "tracing"]
posix_console = ["posix", "console"]

# Use the std module
std = []
# Use POSIX APIs
posix = ["iceoryx2-bb-posix"]

# Enables logging to buffer
buffer = []
# Enables logging to file
file = []
# Enables logging to console
console = []
# Enables https://crates.io/crates/log as default logger
log = ["dep:log"]
# Enables https://crates.io/crates/tracing as default logger
tracing = ["dep:tracing"]

[dependencies]
iceoryx2-log-types = { workspace = true }
iceoryx2-pal-concurrency-sync = { workspace = true }
iceoryx2-bb-posix = { workspace = true, optional = true }

log = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
