[package]
name = "iceoryx2-pal-os-api"
description = "iceoryx2: [internal] OS api layer for OS specific features"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
# Use https://crates.io/crates/libc for the platform abstraction. This simplifies
# cross-compilation since bindgen is not required anymore. Unfortunately, the libc crate
# does not offer all the functionality iceoryx2 requires on all of the supported
# platforms. Therefore, only a subset of the supported platforms will work with this
# feature flag.
libc_platform = ["iceoryx2-pal-posix/libc_platform", "dep:libc"]

[build-dependencies]
cc = { workspace = true }
bindgen = { workspace = true }

[dependencies]
iceoryx2-pal-posix = { workspace = true }
libc = { workspace = true, optional = true }
