[package]
name = "iceoryx2-conformance-tests"
description = "iceoryx2: Conformance tests for iceoryx2 components and extensions"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
iceoryx2 = { workspace = true }
iceoryx2-bb-concurrency = { workspace = true }
iceoryx2-bb-conformance-test-macros = { workspace = true }
iceoryx2-bb-container = { workspace = true }
iceoryx2-bb-elementary = { workspace = true }
iceoryx2-bb-derive-macros = { workspace = true }
iceoryx2-log = { workspace = true }
iceoryx2-bb-posix = { workspace = true }
iceoryx2-bb-testing = { workspace = true }
iceoryx2-cal = { workspace = true }
iceoryx2-pal-testing = { workspace = true }
