[package]
name = "iceoryx2-bb-memory"
description = "Iceoryx2: [internal] allocators and tools for memory management"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
iceoryx2-bb-lock-free = { workspace = true }
iceoryx2-bb-elementary = { workspace = true }
iceoryx2-bb-log = { workspace = true }
iceoryx2-bb-posix = { workspace = true }

tiny-fn = { workspace = true }
lazy_static = { workspace = true }
pin-init = { workspace = true }

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
