[package]
name = "posix-nostd-publish-subscribe"
description = "a nostd publish-subscribe example that uses the posix abstraction"
license = { workspace = true }
edition = { workspace = true }
version = { workspace = true }
rust-version = { workspace = true }

[[example]]
name = "posix_nostd_publish_subscribe_publisher"
path = "src/publisher.rs"

[[example]]
name = "posix_nostd_publish_subscribe_subscriber"
path = "src/subscriber.rs"

[dependencies]
posix-nostd-common = { workspace = true }

iceoryx2-bb-loggers = { workspace = true }
iceoryx2-bb-posix = { workspace  = true }
iceoryx2 = { workspace = true }
