[package]
name = "iceoryx2-bb-posix"
description = "iceoryx2: [internal] high level safe abstractions for low level unsafe posix constructs"
categories = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[features]
acl = ["iceoryx2-pal-posix/acl"]

[dependencies]
iceoryx2-bb-container = { workspace = true }
iceoryx2-bb-system-types = { workspace = true }
iceoryx2-bb-elementary = { workspace = true }
iceoryx2-bb-log = { workspace = true }
iceoryx2-pal-posix = { workspace = true }
iceoryx2-pal-configuration = { workspace = true }
iceoryx2-pal-concurrency-sync = { workspace = true }

lazy_static = { workspace = true }
bitflags = { workspace = true }
enum-iterator = { workspace = true }
tiny-fn = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
iceoryx2-bb-testing = { workspace = true }
generic-tests = { workspace = true }
